CONST NumHullfuncNames  = 41;
CONST __HullfuncNames_0 : STRING[44] = 'Alchemy: 9 Supplies -> 1 Tri + 1 Dur + 1 Mol';
CONST __HullfuncNames_1 : STRING[39] = 'Alchemy: 1 Mineral + 1 Supply -> 1 Fuel';
CONST __HullfuncNames_2 : STRING[28] = 'Alchemy: 1 Mineral -> 1 Fuel';
CONST __HullfuncNames_3 : STRING[21] = 'Heats planets to 50øF';
CONST __HullfuncNames_4 : STRING[21] = 'Cools planets to 50øF';
CONST __HullfuncNames_5 : STRING[22] = 'Heats planets to 100øF';
CONST __HullfuncNames_6 : STRING[23] = 'Experimental Hyperdrive';
CONST __HullfuncNames_7 : STRING[23] = 'Gravitonic Accelerators';
CONST __HullfuncNames_8 : STRING[28] = 'Scans all wormholes in range';
CONST __HullfuncNames_9 : STRING[8] = 'Gambling';
CONST __HullfuncNames_10 : STRING[25] = 'De-cloaking Tachyon field';
CONST __HullfuncNames_11 : STRING[16] = 'Imperial Assault';
CONST __HullfuncNames_12 : STRING[10] = 'Chunneling';
CONST __HullfuncNames_13 : STRING[8] = 'Ramscoop';
CONST __HullfuncNames_14 : STRING[24] = 'Bioscanner (100% chance)';
CONST __HullfuncNames_15 : STRING[24] = 'Advanced Cloaking Device';
CONST __HullfuncNames_16 : STRING[15] = 'Cloaking Device';
CONST __HullfuncNames_17 : STRING[23] = 'Bioscanner (20% chance)';
CONST __HullfuncNames_18 : STRING[31] = 'Glory Device (10% to own units)';
CONST __HullfuncNames_19 : STRING[31] = 'Glory Device (20% to own units)';
CONST __HullfuncNames_20 : STRING[10] = 'Unclonable';
CONST __HullfuncNames_21 : STRING[13] = 'Clonable once';
CONST __HullfuncNames_22 : STRING[10] = 'Ungiveable';
CONST __HullfuncNames_23 : STRING[13] = 'Giveable once';
CONST __HullfuncNames_24 : STRING[20] = 'Level 2 Tractor Beam';
CONST __HullfuncNames_25 : STRING[12] = 'Tractor Beam';
CONST __HullfuncNames_26 : STRING[27] = 'Chunneling: chunnels itself';
CONST __HullfuncNames_27 : STRING[27] = 'Chunneling: chunnels others';
CONST __HullfuncNames_28 : STRING[26] = 'Chunneling: chunnel target';
CONST __HullfuncNames_29 : STRING[27] = 'Immune to attacking planets';
CONST __HullfuncNames_30 : STRING[13] = 'Ore condenser';
CONST __HullfuncNames_31 : STRING[8] = 'Boarding';
CONST __HullfuncNames_32 : STRING[26] = 'Immune to Anti-Cloak ships';
CONST __HullfuncNames_33 : STRING[12] = 'Crew Academy';
CONST __HullfuncNames_34 : STRING[22] = 'Can repair other ships';
CONST __HullfuncNames_35 : STRING[29] = 'Full weaponry even if damaged';
CONST __HullfuncNames_36 : STRING[16] = 'Hardened engines';
CONST __HullfuncNames_37 : STRING[9] = 'Commander';
CONST __HullfuncNames_38 : STRING[10] = 'Ion shield';
CONST __HullfuncNames_39 : STRING[24] = 'Hardened cloaking device';
CONST __HullfuncNames_40 : STRING[34] = 'Advanced de-cloaking Tachyon field';
CONST HullfuncNames : ARRAY[1..41] OF WORD = (
    Ofs(__HullfuncNames_0),
    Ofs(__HullfuncNames_1),
    Ofs(__HullfuncNames_2),
    Ofs(__HullfuncNames_3),
    Ofs(__HullfuncNames_4),
    Ofs(__HullfuncNames_5),
    Ofs(__HullfuncNames_6),
    Ofs(__HullfuncNames_7),
    Ofs(__HullfuncNames_8),
    Ofs(__HullfuncNames_9),
    Ofs(__HullfuncNames_10),
    Ofs(__HullfuncNames_11),
    Ofs(__HullfuncNames_12),
    Ofs(__HullfuncNames_13),
    Ofs(__HullfuncNames_14),
    Ofs(__HullfuncNames_15),
    Ofs(__HullfuncNames_16),
    Ofs(__HullfuncNames_17),
    Ofs(__HullfuncNames_18),
    Ofs(__HullfuncNames_19),
    Ofs(__HullfuncNames_20),
    Ofs(__HullfuncNames_21),
    Ofs(__HullfuncNames_22),
    Ofs(__HullfuncNames_23),
    Ofs(__HullfuncNames_24),
    Ofs(__HullfuncNames_25),
    Ofs(__HullfuncNames_26),
    Ofs(__HullfuncNames_27),
    Ofs(__HullfuncNames_28),
    Ofs(__HullfuncNames_29),
    Ofs(__HullfuncNames_30),
    Ofs(__HullfuncNames_31),
    Ofs(__HullfuncNames_32),
    Ofs(__HullfuncNames_33),
    Ofs(__HullfuncNames_34),
    Ofs(__HullfuncNames_35),
    Ofs(__HullfuncNames_36),
    Ofs(__HullfuncNames_37),
    Ofs(__HullfuncNames_38),
    Ofs(__HullfuncNames_39),
    Ofs(__HullfuncNames_40));
