[Colors]

;       Black      0       DarkGray      8
;       Blue       1       LightBlue     9
;       Green      2       LightGreen    10
;       Cyan       3       LightCyan     11
;       Red        4       LightRed      12
;       Magenta    5       LightMagenta  13
;       Brown      6       Yellow        14
;       LightGray  7       White         15

PlanetInfo      = 10
OldPlanetInfo   = 2
BaseInfo        = 9
ShipInfo        = 3
StormInfo       = 2
WormInfo        = 5
NeutralPlanet   = 15
WeakStorm       = 2
ModerateStorm   = 14
DangerousStorm  = 4
Wormhole        = 13
FlyPath         = 5
TowPath         = 14
Trace           = 5
DistLine        = 6
Message         = 3
HighLight/      = 14
HighLight_      = 15
HighLight*      = 13

;       Profile = ProfileName,PlanetColor,BaseColor,ShipColor,MineColor

Profile         = Own,9,11,2,3
Profile         = Enemy,14,12,12,5
Profile         = Ally,4,10,3,11

[Interface]
AutoScroll             = On
StickyMouse            = On
LargePlanets           = On
PlanetNames            = On
SmallFont              = On
KeepWayPoints          = Off
AutoUseGravity         = On
DullMissions           = Off
DullMessages           = Off
ShowFinalHappy         = On
AltWormholes           = On
ScreenSaverTime        = 1
DeleteRST              = On
ScrambleShipNames      = Off
ShowMaxPop             = On
ShowColonistPrediction = Off
ShowCombatStrength     = Off
ShowMapBorder          = On
ShowCheckMark          = On
ShowScoreValue         = Off
AutoDisapprove         = Off
ConfirmNotes           = Off
ScoringMethod          = AutoScore

[System]
HelpFile        = VPA.HLP
ResourceFile    = RESOURCE.PLN
BadVideoOrMouse = No
; Font = sanserif.fnt
